name: Run Scraping Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CALL_ME: ${{ secrets.CALL_ME }}
      ANOTHER_ONE: ${{ secrets.ANOTHER_ONE }}
      THIS_ONE: ${{ secrets.THIS_ONE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python main.py
      - name: Commit results
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          fi
